version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.5-node
    steps:
      - checkout
      - run:
        name: Install bundle
        command: bundle install

workflows:
  version: 2
  build:
    jobs:
      - build

